# Generated by Django 5.0.1 on 2024-01-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Spending",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(max_length=255)),
                ("amount", models.FloatField()),
                ("spent_at", models.DateTimeField()),
                ("currency", models.CharField(choices=[("HUF", "HUF"), ("USD", "USD")], max_length=3)),
            ],
        ),
    ]
